spring:
  application:
    name: levelup
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: 'classpath:db/migration/changeLog.xml'
    enabled: true
server:
  port: 8081
  servlet:
    context-path: /levelup
levelup:
  application:
    value: 123
    values:
      - 'Значение1'
      - 'Значение2'
      - 'Значение3'
#  report:
#    type: pdf